export type PresentationComponent = {
  id: string;
  label: string;
  section: string;
  purpose: string;
  technicalSummary: string;
  dataFlow: string;
  sourceFiles: string[];
  technologies: string[];
  assistantContext: string;
};

export type PresentationChapter = {
  id: string;
  headline: string;
  supporting: string;
  section: string;
  componentIds: string[];
};

export type PresentationAssistantContext = {
  chapter: string;
  section: string;
  projectContext: string;
  currentComponent: PresentationComponent | null;
  selectedBimContext?: string;
};

export const presentationComponents: PresentationComponent[] = [
  { id: 'landing-hero', label: 'Landing Hero', section: 'Public experience', purpose: 'Establishes ARCH_TECH as a platform for complex developments.', technicalSummary: 'Editorial landing composition with project navigation and accessibility-aware motion.', dataFlow: 'Localized landing content → Hero → public project routes.', sourceFiles: ['src/components/landing/Hero.tsx', 'src/pages/public/LandingPage.tsx'], technologies: ['React', 'i18next', 'CSS'], assistantContext: 'The landing hero introduces large-scale development and routes visitors into the public portfolio.' },
  { id: 'portal', label: 'Portal', section: 'Platform', purpose: 'Coordinates project work across client, architect, and admin roles.', technicalSummary: 'Role-scoped shell and guarded routes present the same project data in focused workspaces.', dataFlow: 'Session → route guard → PortalShell → project services.', sourceFiles: ['src/components/portal/PortalShell.tsx', 'src/router/AppRouter.tsx'], technologies: ['React Router', 'localStorage', 'JSON Server'], assistantContext: 'The portal turns project information into role-specific coordination workspaces.' },
  { id: 'kpi-cards', label: 'KPI Cards', section: 'Project Intelligence', purpose: 'Make current portfolio signals readable at a glance.', technicalSummary: 'Deterministic project metrics are rendered from current project relations.', dataFlow: 'Project services → derived metrics → portal KPI cards.', sourceFiles: ['src/pages/admin/AdminOverviewPage.tsx', 'src/services/portfolioInsightsService.ts'], technologies: ['React', 'TypeScript'], assistantContext: 'KPI cards summarize current operational signals; they do not forecast outcomes.' },
  { id: 'site-intelligence', label: 'Site Intelligence', section: 'Project Intelligence', purpose: 'Adds current environmental context to site planning discussions.', technicalSummary: 'A resilient service combines location, weather, and seismic providers with local failure states.', dataFlow: 'Location query → external providers → contextual panel.', sourceFiles: ['src/components/portal/PortalCommon.tsx', 'src/services/externalContextService.ts'], technologies: ['Open-Meteo', 'OpenStreetMap', 'USGS'], assistantContext: 'Site Intelligence supplies contextual observations for planning, not predictive safety conclusions.' },
  { id: 'garnier-assistant', label: 'Garnier Assistant', section: 'Platform', purpose: 'Provides a conversational guide to the public platform and presentation.', technicalSummary: 'One assistant service sends an optional context envelope to the existing webhook and falls back locally.', dataFlow: 'Prompt + context → existing assistant service → n8n webhook or local explanation.', sourceFiles: ['src/components/landing/LandingAssistantLauncher.tsx', 'src/services/publicAssistantService.ts', 'src/services/aiService.ts'], technologies: ['React', 'fetch', 'n8n'], assistantContext: 'Garnier Assistant can explain the current presentation component without replacing the existing assistant.' },
  { id: 'bim-viewer', label: 'BIM Viewer', section: 'La Lima BIM', purpose: 'Lets teams inspect a large-scale development in a real-time engineering workspace.', technicalSummary: 'The viewport owns the WebGL container and connects engine callbacks to lightweight application state.', dataFlow: 'IFC or La Lima context → BimEngine → viewport callbacks → inspector and explorer.', sourceFiles: ['src/components/bim/BimViewport.tsx', 'src/bim/engine/BimEngine.ts'], technologies: ['Three.js', 'That Open Components', 'WebIFC'], assistantContext: 'The BIM Viewer is a technical workspace for inspecting IFC models and the La Lima concept site.' },
  { id: 'model-explorer', label: 'Model Explorer', section: 'BIM Exploration', purpose: 'Organizes available scene elements into a searchable professional register.', technicalSummary: 'Explorer groups supplied scene metadata and synchronizes with 3D selection.', dataFlow: 'Scene metadata → ModelInteraction → explorer groups → selected elements.', sourceFiles: ['src/components/bim/BimModelExplorer.tsx', 'src/bim/interaction/modelInteraction.ts'], technologies: ['React', 'Three.js'], assistantContext: 'Model Explorer reflects real scene metadata and keeps its selection synchronized with the 3D view.' },
  { id: 'search', label: 'Search', section: 'BIM Exploration', purpose: 'Finds relevant elements by actual available metadata.', technicalSummary: 'The search filters supplied name, category, type, zone, and element identifiers.', dataFlow: 'Search input → metadata filter → explorer results → selection.', sourceFiles: ['src/components/bim/BimModelExplorer.tsx', 'src/bim/interaction/modelInteraction.ts'], technologies: ['TypeScript', 'React'], assistantContext: 'Search filters real element metadata; it does not infer unrecorded BIM properties.' },
  { id: 'inspector', label: 'Inspector', section: 'BIM Analysis', purpose: 'Surfaces available element identity, classification, location, material, and status data.', technicalSummary: 'The inspector reads extracted IFC or scene details and only renders available fields.', dataFlow: 'Selection → property extraction → inspector groups.', sourceFiles: ['src/components/panels/PropertiesPanel.tsx', 'src/bim/properties/propertyExtractor.ts'], technologies: ['WebIFC', 'React'], assistantContext: 'Inspector content comes from available BIM or scene metadata rather than invented properties.' },
  { id: 'selection', label: 'Selection', section: 'BIM Exploration', purpose: 'Connects an element in the scene to focused inspection actions.', technicalSummary: 'Selection uses existing highlighter and reusable overlay helpers without cloning source geometry.', dataFlow: 'Pointer input → ModelInteraction or Highlighter → store → panels.', sourceFiles: ['src/bim/engine/BimEngine.ts', 'src/bim/interaction/modelInteraction.ts'], technologies: ['Three.js', 'That Open Components'], assistantContext: 'Selection connects the scene, explorer, and inspector while preserving source geometry.' },
  { id: 'multi-selection', label: 'Multi-selection', section: 'BIM Exploration', purpose: 'Supports collective focus, hiding, and isolation of multiple relevant elements.', technicalSummary: 'Modifier selection maintains a deterministic target set and shared helper overlays.', dataFlow: 'Modifier click → target set → visibility or focus action.', sourceFiles: ['src/bim/interaction/modelInteraction.ts', 'src/components/bim/BimInteractionPanel.tsx'], technologies: ['Three.js', 'React'], assistantContext: 'Multi-selection lets reviewers operate on several real scene elements together.' },
  { id: 'distance', label: 'Distance', section: 'BIM Analysis', purpose: 'Measures a direct real-world distance between two points.', technicalSummary: 'Native measurement tooling snaps world coordinates and formats meter values.', dataFlow: 'Viewport point picks → LengthMeasurement → in-scene dimension.', sourceFiles: ['src/bim/engine/BimEngine.ts', 'src/components/toolbar/BottomToolbar.tsx'], technologies: ['That Open Components'], assistantContext: 'Distance measurement is a non-destructive world-coordinate tool expressed in meters.' },
  { id: 'polyline', label: 'Polyline', section: 'BIM Analysis', purpose: 'Measures connected route or perimeter segments as one total.', technicalSummary: 'A lightweight line overlay retains real picked world points and segment totals.', dataFlow: 'Viewport point picks → polyline state → overlay and toolbar summary.', sourceFiles: ['src/bim/engine/BimEngine.ts', 'src/bim/interaction/measurementMath.ts'], technologies: ['Three.js', 'TypeScript'], assistantContext: 'Polyline measurement reports connected segment lengths and a total without changing the model.' },
  { id: 'area', label: 'Area', section: 'BIM Analysis', purpose: 'Measures a polygonal footprint or surface in square meters.', technicalSummary: 'Native area measurement closes a world-space polygon and renders its in-scene value.', dataFlow: 'Viewport point picks → AreaMeasurement → area label.', sourceFiles: ['src/bim/engine/BimEngine.ts', 'src/bim/interaction/measurementMath.ts'], technologies: ['That Open Components', 'Three.js'], assistantContext: 'Area measurement builds a non-destructive world-space polygon and reports square meters.' },
  { id: 'section-plane', label: 'Section Plane', section: 'BIM Analysis', purpose: 'Reveals interior relationships through one controlled cut plane.', technicalSummary: 'A single stateful clipper plane supports axis, offset, inversion, and reset.', dataFlow: 'Section controls → BimEngine → Clipper → renderer materials.', sourceFiles: ['src/bim/engine/BimEngine.ts', 'src/components/toolbar/BottomToolbar.tsx'], technologies: ['That Open Components', 'Three.js'], assistantContext: 'The section plane is a reversible viewport cut that coexists with IFC and La Lima geometry.' },
  { id: 'saved-views', label: 'Saved Views', section: 'BIM Exploration', purpose: 'Captures repeatable camera positions for important review moments.', technicalSummary: 'Local viewpoints preserve camera mode, target, and current IFC or scene selection.', dataFlow: 'Camera state → BimViewpoint → local store → restore action.', sourceFiles: ['src/components/panels/ViewpointsPanel.tsx', 'src/bim/engine/BimEngine.ts'], technologies: ['Zustand', 'React'], assistantContext: 'Saved Views restore a captured camera state and selection without a backend dependency.' },
  { id: 'day-overcast', label: 'Day / Overcast', section: 'Visual Engine', purpose: 'Offers two architectural daylight readings for a development review.', technicalSummary: 'A shared lighting lifecycle adjusts existing light colors and intensity without rebuilding the scene.', dataFlow: 'Preset control → SceneLighting → shared light pair.', sourceFiles: ['src/bim/engine/sceneLighting.ts', 'src/bim/engine/BimEngine.ts'], technologies: ['Three.js'], assistantContext: 'Day and Overcast are controlled lighting presets that reuse the same scene lights.' },
  { id: 'quality-profiles', label: 'Performance / Balanced / Presentation', section: 'Visual Engine', purpose: 'Matches viewer fidelity to the review context and available hardware.', technicalSummary: 'Profiles control DPR, tone mapping, adaptive resolution, and shared lighting intensity.', dataFlow: 'Profile selection → render quality → renderer and diagnostics.', sourceFiles: ['src/bim/engine/renderQuality.ts', 'src/bim/engine/BimEngine.ts'], technologies: ['WebGL', 'Three.js'], assistantContext: 'Quality profiles tune rendering cost without changing BIM geometry or project data.' },
];

export const presentationChapters: PresentationChapter[] = [
  { id: 'arch-tech', headline: 'ARCH_TECH', supporting: 'A clear platform for developments that must perform at scale.', section: 'Opening', componentIds: ['landing-hero'] },
  { id: 'large-scale-development', headline: 'Large-Scale Development', supporting: 'From industrial districts to corporate campuses, complexity becomes momentum.', section: 'Public experience', componentIds: ['landing-hero'] },
  { id: 'platform', headline: 'Platform', supporting: 'One connected place for every project conversation that matters.', section: 'Platform', componentIds: ['portal', 'garnier-assistant'] },
  { id: 'project-intelligence', headline: 'Project Intelligence', supporting: 'Current signals make the next conversation more focused.', section: 'Project Intelligence', componentIds: ['kpi-cards', 'site-intelligence'] },
  { id: 'la-lima-bim', headline: 'La Lima BIM', supporting: 'A masterplan becomes a space to inspect, discuss, and align.', section: 'La Lima BIM', componentIds: ['bim-viewer'] },
  { id: 'bim-exploration', headline: 'BIM Exploration', supporting: 'Every relevant element stays within reach of the team.', section: 'BIM Exploration', componentIds: ['model-explorer', 'search', 'selection', 'multi-selection', 'saved-views'] },
  { id: 'bim-analysis', headline: 'BIM Analysis', supporting: 'Measurements and sections turn visual review into clear evidence.', section: 'BIM Analysis', componentIds: ['inspector', 'distance', 'polyline', 'area', 'section-plane'] },
  { id: 'visual-engine', headline: 'Visual Engine', supporting: 'The same model can be read for speed, balance, or presentation.', section: 'Visual Engine', componentIds: ['day-overcast', 'quality-profiles'] },
  { id: 'garnier-assistant', headline: 'Garnier Assistant', supporting: 'A guide ready to translate the platform into the next conversation.', section: 'Platform', componentIds: ['garnier-assistant'] },
  { id: 'closing', headline: 'Closing', supporting: 'ARCH_TECH brings development intelligence, project coordination, and BIM together.', section: 'Closing', componentIds: ['portal', 'bim-viewer', 'garnier-assistant'] },
];

export const getPresentationComponent = (id: string | null): PresentationComponent | null =>
  presentationComponents.find((component) => component.id === id) ?? null;
