export { LoginOverlay } from '../auth/LoginOverlay';
export { PublicProjectPage } from '../../pages/public/PublicProjectPage';
export { DashboardProjectPage } from '../../pages/portal/project/DashboardProjectPage';
export { ForbiddenPage, NotFoundPage, ServiceUnavailablePage, PortalEmptyState, ExternalContextPanel, CreateProjectModal, PortalAIAssistantView } from './PortalCommon';
export { PortalShell, PORTAL_NAV_ITEMS, usePortalShell } from './PortalShell';
export { ClientOverviewPage as DashboardPage, ClientOverviewPage } from '../../pages/client/ClientOverviewPage';
export { ClientProjectsPage } from '../../pages/client/ClientProjectsPage';
export { ClientDocumentsPage } from '../../pages/client/ClientDocumentsPage';
export { ClientApprovalsPage } from '../../pages/client/ClientApprovalsPage';
export { ClientInsightsPage } from '../../pages/client/ClientInsightsPage';
export { ClientAssistantPage } from '../../pages/client/ClientAssistantPage';
export { ArchitectOverviewPage as ArchitectDashboardPage, ArchitectOverviewPage } from '../../pages/architect/ArchitectOverviewPage';
export { ArchitectProjectsPage } from '../../pages/architect/ArchitectProjectsPage';
export { ArchitectApprovalsPage } from '../../pages/architect/ArchitectApprovalsPage';
export { ArchitectDocumentsPage } from '../../pages/architect/ArchitectDocumentsPage';
export { ArchitectInsightsPage } from '../../pages/architect/ArchitectInsightsPage';
export { ArchitectAssistantPage } from '../../pages/architect/ArchitectAssistantPage';
export { AdminOverviewPage as AdminDashboardPage, AdminOverviewPage } from '../../pages/admin/AdminOverviewPage';
export { AdminProjectsPage } from '../../pages/admin/AdminProjectsPage';
export { AdminPeoplePage } from '../../pages/admin/AdminPeoplePage';
export { AdminApprovalsPage } from '../../pages/admin/AdminApprovalsPage';
export { AdminAnalyticsPage } from '../../pages/admin/AdminAnalyticsPage';
export { AdminAssistantPage } from '../../pages/admin/AdminAssistantPage';
export { AdminNewsPage } from '../../pages/admin/AdminNewsPage';
